### ISSUE TITLE
이미지 등록시, 경계선 영역이 일부 이상하게 나타남

### ISSUE THREAD

**Issue by homecheck-garden** [homecheck-garden/webgl-canvas#1]
![image](https://github.com/homecheck-garden/webgl-canvas/assets/102957326/289b09ba-9eff-4481-baf6-bf0832949581)

위 이미지 참고 부탁드립니다.

**Comment by leemin0830** [comment]
재현 환경(브라우저, 디바이스 etc) 및 스텝 부탁드리겠습니다.

**Comment by homecheck-garden** [comment]
이후 동일한 증상 재현을 위해 노력했으나 불가능했습니다.
당시 증상으로보건데 fabric js 문제에 가까워보여 클로즈하겠습니다.

**Comment by leemin0830** [comment]
최근 푸시된 내용중 좌표계를 재설정하는 로직이 추가되었습니다. 가능성있는 해결책으로 생각이 되지만 혹시 다시 문제가 발생하면 살펴보도록 하겠습니다.
