### ISSUE TITLE
객체 생성 반응이 직관적이지 않음.

### ISSUE THREAD

**Issue by homecheck-garden** [homecheck-garden/webgl-canvas#3]
버튼 클릭후, 일정 시간이 지나거나 포커스가 캔버스를 향해야 객체가 생성되는 듯 함
Point Circle 등등
![image](https://github.com/homecheck-garden/webgl-canvas/assets/102957326/530cde73-6f4f-4cca-9499-ec24087a38fd)

**Comment by leemin0830** [comment]
재현 환경 확인 부탁드립니다.

**Comment by homecheck-garden** [comment]
마지막 푸시에서 해결된듯 합니다.
